# Generated by Django 4.0.3 on 2022-04-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1500, verbose_name='Content')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('rate', models.PositiveIntegerField(default=0, verbose_name='Rate')),
                ('status', models.CharField(choices=[('0', 'new'), ('1', 'moderated')], default='0', max_length=30, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
            ],
            options={
                'verbose_name': 'quote',
                'verbose_name_plural': 'quotes',
                'db_table': 'quotes',
            },
        ),
    ]
