# Generated by Django 4.0.3 on 2022-04-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
    ]
